### ISSUE TITLE
Missing a license

### ISSUE THREAD

**Issue by Panquesito7** [FunctionDJ/project-plus-website#19]
### Description

We should add a license to this repository. This way, people will know what and what not they can do with this repository, permissions, notices, etc.. The most permissive and good license is the [**MIT license**](https://mit-license.org). Depending on what you'd like other users to do with the code, you can choose other licenses as well.

Check this page for more information: https://choosealicense.com/
Great project, by the way! Thanks. 🙂

**Comment by FunctionDJ** [comment]
@Panquesito7 Thanks a lot for letting me know. I've decided for a strong copyleft license, GNU AGPLv3.
